"use client";import {useEffect,useState} from "react";
const talent="https://drub-creator-vault.vercel.app/creators",join="https://drub-creator-vault.vercel.app/join";
export default function Home(){const [y,setY]=useState(0);useEffect(()=>{const f=()=>{setY(scrollY);document.documentElement.style.setProperty("--scroll",String(scrollY))};addEventListener("scroll",f,{passive:true});const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("in")}),{threshold:.14});document.querySelectorAll(".reveal,.work,.cap").forEach(el=>io.observe(el));const move=(e:MouseEvent)=>{document.documentElement.style.setProperty("--mx",e.clientX+"px");document.documentElement.style.setProperty("--my",e.clientY+"px")};addEventListener("mousemove",move);return()=>{removeEventListener("scroll",f);removeEventListener("mousemove",move);io.disconnect()}},[]);
return <main><div className="cursorGlow"/><div className="noise"/>
<nav><a className="brand" href="#">DRUB<span>•</span></a><div className="navlinks"><a href="#work">Work</a><a href="#capabilities">Capabilities</a><a href={talent}>Talent Network</a><a href="#contact" className="pill">Start a project</a></div></nav>
<section className="hero"><div className="grid"/><div className="orb o1" style={{transform:`translate3d(0,${y*.08}px,0)`}}/><div className="orb o2" style={{transform:`translate3d(0,${-y*.05}px,0)`}}/><p className="eyebrow">DUBAI / UAE · INDEPENDENT CREATIVE STUDIO</p><h1>WE CREATE<br/><i>EXPERIENCES</i><br/>PEOPLE <span>FEEL.</span></h1><div className="herofoot"><p>Experiential marketing, creator campaigns and production built for the physical and digital world.</p><a href="#work" className="round">↓</a></div></section>
<section className="ticker"><div>EXPERIENTIAL ✦ CREATOR NETWORK ✦ PRODUCTION ✦ ACTIVATIONS ✦ UGC ✦ CONTENT ✦ EXPERIENTIAL ✦ CREATOR NETWORK ✦</div></section>
<section id="work" className="section"><div className="label">01 / SELECTED WORK</div><div className="statement reveal">Not campaigns made to <em>fill feeds.</em><br/>Ideas built to <strong>enter culture.</strong></div><div className="workgrid"><article className="work w1"><div className="num">01</div><div><b>BEAUTYWORLD DUBAI</b><p>Launch · Content · Experience</p></div></article><article className="work w2"><div className="num">02</div><div><b>BRAND EXPERIENCES</b><p>Retail · Events · Activations</p></div></article><article className="work w3"><div className="num">03</div><div><b>CREATOR CAMPAIGNS</b><p>UGC · Influence · Social</p></div></article></div></section>
<section id="capabilities" className="section capabilities"><div className="label">02 / WHAT WE DO</div><div className="cap"><span>01</span><h2>EXPERIENTIAL</h2><p>Brand activations, launches, exhibitions and physical experiences engineered for attention.</p><b>↗</b></div><div className="cap"><span>02</span><h2>CREATORS & UGC</h2><p>Creator-led campaigns backed by our own growing UAE talent network.</p><a href={talent}>EXPLORE NETWORK ↗</a></div><div className="cap"><span>03</span><h2>PRODUCTION</h2><p>Photography, film, CGI and campaign content designed to move across every screen.</p><b>↗</b></div></section>
<section className="network reveal"><div className="scan"/><p className="eyebrow">DRUB TALENT NETWORK / LIVE SYSTEM</p><h2>THE RIGHT<br/>FACE. <i>FASTER.</i></h2><p className="networkcopy">Discover creators, models and hostesses across the UAE. Filter. Discover. Shortlist. Request availability.</p><div className="actions"><a href={talent} className="primary">ACCESS THE NETWORK ↗</a><a href={join}>JOIN AS TALENT ↗</a></div><div className="hud"><span>CREATORS</span><span>MODELS</span><span>HOSTESSES</span><span className="live">● LIVE</span></div></section>
<section id="contact" className="contact reveal"><p>HAVE SOMETHING<br/>WORTH <i>BUILDING?</i></p><a href="mailto:reachus@drubme.com">REACHUS@DRUBME.COM ↗</a><div className="contactrow"><span>SHARJAH · UAE</span><span>+971 58 523 4100</span><span>WHATSAPP +971 50 113 4339</span></div></section>
<footer><b>DRUB•</b><span>EXPERIENTIAL / CREATORS / PRODUCTION</span><span>© 2026 DRUB MEDIA</span></footer>
</main>}